// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bSfv-CzfPDZih8Lm-BEwG8x8724ZYEc',
    appId: '1:427670484599:web:b97f922c227c8e0f693872',
    messagingSenderId: '427670484599',
    projectId: 'crud-ads-98fcc',
    authDomain: 'crud-ads-98fcc.firebaseapp.com',
    storageBucket: 'crud-ads-98fcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6lzvjOBY7Zu4HWtp4nJVtfnEC5USBsRg',
    appId: '1:427670484599:android:1719abc5687ac659693872',
    messagingSenderId: '427670484599',
    projectId: 'crud-ads-98fcc',
    storageBucket: 'crud-ads-98fcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC645z1j3S96ZqkM15Kd6Hk8r2PQ0oIKxY',
    appId: '1:427670484599:ios:05eba946684d46b7693872',
    messagingSenderId: '427670484599',
    projectId: 'crud-ads-98fcc',
    storageBucket: 'crud-ads-98fcc.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC645z1j3S96ZqkM15Kd6Hk8r2PQ0oIKxY',
    appId: '1:427670484599:ios:32c76c3df1bd9d64693872',
    messagingSenderId: '427670484599',
    projectId: 'crud-ads-98fcc',
    storageBucket: 'crud-ads-98fcc.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
